name: NodeJS with Webpack

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install node module
      run: |
        npm install

    - name: Create dir for deploy
      run: |
        mkdir ./deploy
        mkdir ./deploy/controller_ui
        mkdir ./deploy/z_uno_compiler
        mkdir ./deploy/controller_ui/release
        mkdir ./deploy/z_uno_compiler/release

    - name: Build controller_ui
      run: |
        npm run build
        mv ./build/* ./deploy/controller_ui/release

    - name: Build z-uno-compiler
      run: |
        npm run build_zuno
        mv ./build/* ./deploy/z_uno_compiler/release
  
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./deploy
        user_name: 'amatilda'
        user_email: '<kpk@z-wave.me>'
        commit_message: 'Auto-generated commit'
        publish_branch: 'gh-pages'